name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: mkdir
      run:  mkdir __build__
    - name: cd
      run: cd __build__
    - name: cmake
      run: cmake .. && cmake --build . && ctest -V .
